### ISSUE TITLE
5.0.0-alpha.2 Label text doesn't update on B&W ePaper FeatherWing

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_CircuitPython_SSD1675#2]
Adafruit Feather M4 Express with samd51j19
5.0.0-alpha.2 on 2019-09-04
CP Lib Bundle 20190906

Maybe this belongs in circuitpython instead of here, but this issue only seems to affect the 2-color EPD.

Sorry for the code size, wanted to make sure it worked on other displays.

This code works on other FeatherWings, including TFTs, OLED, and the 3-color EPD. But text does not update after the first display on the 2-color EPD. It goes through its flashing motions, but same text appears again.

print() output shows the code is progressing through it's loops on the 2-color EPD:

> Adafruit Feather M4 Express with samd51j19 5.0.0-alpha.2 on 2019-09-04 20190906
> 0.0
> 0 13144063000000
> 179.999
> 1 13324181000000
> 180.0
> 2 13504201000000

```
import os
import time
import board
import terminalio
import displayio
from adafruit_display_text.label import Label
from adafruit_displayio_ssd1306 import SSD1306
from adafruit_featherwing import minitft_featherwing
from adafruit_ili9341 import ILI9341
from adafruit_hx8357 import HX8357
from adafruit_ssd1675 import SSD1675
from adafruit_il0373 import IL0373


# CicruitPython 5.0.0-alpha.2 displayio EPD Test

# PyPortal
pyportal = False
# ...OR...
# Feather M4 Express + choose your own adventure:
oled = False
minitft = False
ili9341 = False
hx8357 = False
ssd1675 = True
il0373 = False

epaper = False
if ssd1675 or il0373:
    epaper = True


if pyportal:
    display = board.DISPLAY
else:
    displayio.release_displays()
    cs = board.D9
    dc = board.D10

if oled:
    # Adafruit I2C OLED FeatherWing
    i2c = board.I2C()
    display_bus = displayio.I2CDisplay(i2c, device_address=0x3c)
    display = SSD1306(display_bus, width=128, height=32)

if minitft:
    # Adafruit Mini Color TFT with Joystick FeatherWing
    display = minitft_featherwing.MiniTFTFeatherWing().display

if ili9341:
    # Adafruit 2.4" TFT FeatherWing
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs)
    display = ILI9341(display_bus, width=320, height=240)

if hx8357:
    # Adafruit 3.5" TFT FeatherWing
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs)
    display = HX8357(display_bus, width=480, height=320)

if ssd1675:
    # Adafruit 2.13" Black and White FeatherWing
    # https://github.com/adafruit/Adafruit_CircuitPython_SSD1675/blob/master/examples/ssd1675_simpletest.py
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs, baudrate=1000000)
    time.sleep(1)
    display = SSD1675(display_bus, width=250, height=122, rotation=90)

if il0373:
    # Adafruit 2.13" Tri-Color FeatherWing
    # https://github.com/adafruit/Adafruit_CircuitPython_IL0373/blob/master/examples/il0373_simpletest.py
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs, baudrate=1000000)
    time.sleep(1)
    display = IL0373(display_bus, width=212, height=104, rotation=90, highlight_color=0xff0000)


# displayio

SPLASHWIDTH = display.width
SPLASHHEIGHT = display.height
SPLASHMAX = 2
splash = displayio.Group(max_size=SPLASHMAX)

# Group 0
background_bitmap = displayio.Bitmap(SPLASHWIDTH, SPLASHHEIGHT, 1)
background_palette = displayio.Palette(1)
background_palette[0] = 0x0000
background = displayio.TileGrid(background_bitmap, pixel_shader=background_palette)
splash.append(background)

# Group 1
splash.append(displayio.Group(max_size=1, scale=1, x=0, y=0))  #dummy
font = terminalio.FONT
#                             3 80953846000000
text_area = Label(font, text="0123456789012345", color=0xFFFFFF)
text_area.x = 5
text_area.y = 25
splash[1] = text_area

display.show(splash)


with open('/VERSIONS.txt') as f:
    cp_lib_bundle = f.readline().strip()
print(os.uname()[4], os.uname()[3], cp_lib_bundle)

loop = 0
while True:
    if epaper:
        print(display.time_to_refresh)
        time.sleep(display.time_to_refresh)
    else:
        time.sleep(5)

    try:
        print(loop % 10, time.monotonic_ns())
        text_area.text = str(loop % 10) + ' ' + str(time.monotonic_ns())
        display.refresh()
    except RuntimeError as e:  # Refresh too soon
        print(e)

    loop += 1
```

**Comment by ladyada** [comment]
@makermelissa please verify!

**Comment by anecdata** [comment]
Trying the Sprite Sheet Example from the displayio Learn Guide also yields some quirks. 

The B&W EPD FeatherWing will display everything after the first time at x=0 with this code. 

The 3-Color EPD will often not refresh at all as it progresses through the loops, even after a power-down, with this code. However, the 3-Color EPD will [happily](https://gist.github.com/anecdata/cfdcd58805c14a29160e75f3f8b90016) switch back and forth between an `OnDiskBitmap` (e.g., display-ruler.bmp) and `display.show(None)` all day long. 

Works as expected on PyPortal. Sprite Sheet code (modified to add some print()s and the refresh delay handling):
```
import os
import time
import board
import terminalio
import displayio
import adafruit_imageload
from adafruit_display_text.label import Label
from adafruit_ssd1675 import SSD1675
from adafruit_il0373 import IL0373


# CicruitPython 5.0.0-alpha.2
# PyPortal
pyportal = False
# ...OR...
# Feather M4 Express + choose your own EPD adventure:
ssd1675 = True  # 2C
il0373 = False  # 3C
epd_type = 'None'

if pyportal:
    display = board.DISPLAY
else:
    displayio.release_displays()
    cs = board.D9
    dc = board.D10

if ssd1675:
    # Adafruit 2.13" Black and White FeatherWing
    # https://github.com/adafruit/Adafruit_CircuitPython_SSD1675/blob/master/examples/ssd1675_simpletest.py
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs, baudrate=1000000)
    time.sleep(1)
    display = SSD1675(display_bus, width=250, height=122, rotation=90, seconds_per_frame=60)
    epd_type = 'ssd1675_2C'

if il0373:
    # Adafruit 2.13" Tri-Color FeatherWing
    # https://github.com/adafruit/Adafruit_CircuitPython_IL0373/blob/master/examples/il0373_simpletest.py
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs, baudrate=1000000)
    time.sleep(1)
    display = IL0373(display_bus, width=212, height=104, rotation=90, highlight_color=0xff0000, seconds_per_frame=60)
    epd_type = 'il0373_3C'

with open('/VERSIONS.txt') as f:
    cp_lib_bundle = f.readline().strip()
print(os.uname()[4], os.uname()[3], cp_lib_bundle)


# Load the sprite sheet (bitmap)
sprite_sheet, palette = adafruit_imageload.load("/cp_sprite_sheet.bmp",
                                                bitmap=displayio.Bitmap,
                                                palette=displayio.Palette)

# Create a sprite (tilegrid)
sprite = displayio.TileGrid(sprite_sheet, pixel_shader=palette,
                            width = 1,
                            height = 1,
                            tile_width = 16,
                            tile_height = 16)

# Create a Group to hold the sprite
group = displayio.Group(scale=1)

# Add the sprite to the Group
group.append(sprite)

# Add the Group to the Display
display.show(group)

# Set sprite location
group.x = 60  # was 120
group.y = 20  # was 80

# Loop through each sprite in the sprite sheet
source_index = 0
while True:
    sprite[0] = source_index % 6
    source_index += 1

    # time.sleep(2)
    if epd_type is 'None':
        time.sleep(2)
        time_to_refresh = 0
    else:
        time.sleep(display.time_to_refresh)
        time_to_refresh = display.time_to_refresh

    try:
        print(source_index, epd_type, time_to_refresh)
        display.refresh()
    except RuntimeError as e:  # Refresh too soon
        print(source_index, epd_type, time_to_refresh, e)
```

**Comment by anecdata** [comment]
Some progress on the initial 2-Color EPD FeatherWing issue. Simplified code below. Inserting
```
display.show(None)
display.refresh()
```
in every loop allows the text of the label to get updated properly on the 2-Color EPD during every loop. Seems like a boundary condition / element initialization issue that switching to the terminal does cleanly. Much like in the original example, the 3-Color EPD will run the code with or without the switch to the terminal.

Code as follows, does not update the Label properly as shown, but works if you uncomment the block indicated:
```
import os
import time
import board
import terminalio
import displayio
from adafruit_display_text.label import Label
from adafruit_ssd1675 import SSD1675
from adafruit_il0373 import IL0373


# Feather M4 Express + choose your own EPD adventure:
ssd1675 = True
il0373 = False

displayio.release_displays()
cs = board.D9
dc = board.D10

if ssd1675:
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs, baudrate=1000000)
    time.sleep(1)
    display = SSD1675(display_bus, width=250, height=122, rotation=90, seconds_per_frame=10)
elif il0373:
    display_bus = displayio.FourWire(board.SPI(), command=dc, chip_select=cs, baudrate=1000000)
    time.sleep(1)
    display = IL0373(display_bus, width=212, height=104, rotation=90, highlight_color=0xff0000, seconds_per_frame=30)


# displayio

SPLASHWIDTH = display.width
SPLASHHEIGHT = display.height
SPLASHMAX = 2
splash = displayio.Group(max_size=SPLASHMAX)

# Group 0
background_bitmap = displayio.Bitmap(SPLASHWIDTH, SPLASHHEIGHT, 1)
background_palette = displayio.Palette(1)
background_palette[0] = 0x0000
background = displayio.TileGrid(background_bitmap, pixel_shader=background_palette)
splash.append(background)

# Group 1
splash.append(displayio.Group(max_size=1, scale=1, x=0, y=0))  #dummy
font = terminalio.FONT
text_area = Label(font, text="01234567890123456789", color=0xFFFFFF)
text_area.x = 5
text_area.y = 25
splash[1] = text_area


with open('/VERSIONS.txt') as f:
    cp_lib_bundle = f.readline().strip()
print(os.uname()[4], os.uname()[3], cp_lib_bundle)

loop = 0
while True:
    # Wait, then update and display Label

    time.sleep(display.time_to_refresh)
    try:
        text_area.text = str(loop) + ' ' + str(display.time_to_refresh)

        print("Text", loop, display.time_to_refresh)
        display.show(splash)
        display.refresh()
    except RuntimeError as e:  # Refresh too soon
        print(e)

    """ UNCOMMENT THE FOLLOWING BLOCK TO MAKE IT WORK
    # Wait, then display default CircuitPython terminal

    time.sleep(display.time_to_refresh)
    try:
        print("None", loop, display.time_to_refresh)
        display.show(None)
        display.refresh()
    except RuntimeError as e:  # Refresh too soon
        print(e)
    """

    loop += 1
```
- Still unsure why the Sprite Sheet x-coordinate gets set to 0 on the 2-Color.
- I'll try to characterize the 3-Color issue from my second comment better.

**Comment by anecdata** [comment]
Some progress on the 3-Color issue in my second comment. Seems to be some problematic interaction with `imageload`. If I replace:
```
    sprite_sheet, palette = adafruit_imageload.load("/cp_sprite_sheet.bmp",
                                                    bitmap=displayio.Bitmap,
                                                    palette=displayio.Palette)
```
with:
```
    sprite_sheet = displayio.Bitmap(48, 32, 1)  # same size as "/cp_sprite_sheet.bmp"
    palette = displayio.Palette(1)
    palette[0] = 0xff0000
```
Then the display refreshes as expected. With the `imageload` present, the code runs, loops, and prints to the terminal, but the display never refreshes from whatever was on it before the code starts up, even through a power cycle.

**Comment by makermelissa** [comment]
@anecdata, what is the contents of VERSIONS.txt and cp_sprite_sheet.bmp? I'm trying to run this, but don't have those files.

**Comment by anecdata** [comment]
oh, sorry... 

VERSIONS.txt is from the library bundle, you can delete that little block, it's just to demonstrate which machine/CP/bundle I'm running.

cp_sprite_sheet.bmp is from the `displayio` Learn [guide](https://learn.adafruit.com/circuitpython-display-support-using-displayio/sprite-sheet), but I'd think any small BMP would do.

**Comment by tannewt** [comment]
I'm a bit lost as to what issues you are documenting here. Could you please file separate issues for different problems even if they have the same root cause?

I'm super happy to see your example that validates all displays work like the others. However, it's hard to understand exactly which displays you are testing with.

I'd expect all ePaperDisplays to work similarly wrt refreshing because it is shared logic. The monochrome EPD FeatherWing is an oddball though because it doesn't have reset or busy hooked up.

It will also vary with the driver IC whether it can update part of RAM or not. The top level logic is here: https://github.com/adafruit/circuitpython/blob/master/shared-module/displayio/EPaperDisplay.c#L113

**Comment by anecdata** [comment]
I'm happy to close this ands split it into 3 issues under circuitpython if that's best, now that it doesn't appear isolated to this driver.

All of the non-EPD displays I have (PyPortal, 3.5" & 2.4" TFT, OLED, and MiniTFT/Joy FeatherWings) all behave as expected. The 2-Color & 3-Color EPD FeatherWings each show unique quirks with 5.0.0-alpha.2.

Issue 1: 2-Color EPD FeatherWing won't update a displayio Label without an intervening  `display.show(None)` & `display.refresh()`. 3-Color handles this.

Issue 2: 2_Color EPD FeatherWing changes the x-axis to zero on subsequent displays from a [sprite sheet](https://learn.adafruit.com/circuitpython-display-support-using-displayio/sprite-sheet). 3-Color handles this.

Issue 3: 3-Color EPD... I'm still working on isolating and characterizing the issue, but seems to revolve around (imageload?) bitmap images.

re: 
> It will also vary with the driver IC whether it can update part of RAM or not

Does this mean it will refresh the entire display if only part is updated? That's fine. Or will it just not handle that (fail silently)?

This makes me wonder whether a regression suite of more complex displayio examples would be worthwhile. simpletest.py almost always works, but displayio is complex; the uniqueness of I2C & EPD displays, and the timing issues with EPD, add to that.

**Comment by makermelissa** [comment]
Well I can definitely confirm the 2-color EPD issue. It flashes like it's updating, but the number doesn't change. As @tannewt said, the 2-color featherwing is kind of an oddball.

**Comment by anecdata** [comment]
Does the 3-Color EPD FeatherWing have reset and / or busy hooked up (to which pins)? I assumed neither did, and the busy was accounted for by the `display.time_to_refresh` and the reset was just hooked to main board reset (there was an indication of that in a Learn [guide](https://learn.adafruit.com/epaper-display-featherwing-quote-display/arduino-setup)).

**Comment by ladyada** [comment]
reset is connected to the arduino reset. busy is availale on labeled smt pad

**Comment by anecdata** [comment]
Ah, there it is! Presumably not needed with fixed-time refreshes (the 2-Color is happy down to <2 seconds, not sure if that's content-dependent or not).

**Comment by anecdata** [comment]
Issues will be moved to:

- https://github.com/adafruit/circuitpython/issues/2137
- https://github.com/adafruit/circuitpython/issues/2138
- https://github.com/adafruit/circuitpython/issues/2144

Closing this meandering multi-issue.
